### ISSUE TITLE
Delete on transaction does not work

### ISSUE THREAD

**Issue by asartalo** [powersync-ja/sqlite_async.dart#24]
Sorry I might be missing something here so forgive me if this sounds silly.

I have a delete query that works like this:

```dart
    await db.execute(
      'DELETE FROM tasks WHERE id = ?',
      [task.id],
    );
```

...but not this:

```dart
    await db.writeTransaction((tx) async {
      await tx.execute(
        'DELETE FROM tasks WHERE id = ?',
        [task.id],
      );
    });
```

That should work, right? Am I missing something?

**Comment by rkistner** [comment]
That is supposed to work. What is the issue you're seeing? For example any errors, or does the delete not have an effect?

**Comment by asartalo** [comment]
Yeah. It doesn't delete the row when using a transaction. There does not seem to be any errors and no sql errors that I can see.

**Comment by rkistner** [comment]
I'm not able to reproduce the issue myself. Do you have a full code example that can reproduce it?

**Comment by asartalo** [comment]
Hi @rkistner. Just an update. This was a mistake on my part and realized this days ago. The actual problem was in the test code I was running. The caller that uses this snippet did not use `await` so the test was faulty and it succeeding was maybe because the execution was a tiny bit faster when using `db` instead of transaction. Sorry for the inconvenience and thank you for your time making this software. Have a great day!
