### ISSUE TITLE
No ID returned after insert operation using execute

### ISSUE THREAD

**Issue by slymnyg** [powersync-ja/sqlite_async.dart#64]
I am using the sqlite_async package to insert data into a table. However, after performing the insert operation using the execute function, it does not return the ID of the inserted row. This is an issue, as I need the ID to perform further operations.

`
final result = await db.execute('INSERT INTO ${DownloadModel.tableName} (status, name, version, download_url, file_size) values(?,?,?,?,?)', [m['status'], m['name'], m['version'], m['download_url'], m['file_size']]);
`

**Expected behavior:** I would like to retrieve the ID of the newly inserted row after executing the insert command.

**Actual behavior:** The execute function completes without returning the ID of the inserted data.

**Steps to reproduce:**
  1. Execute an insert operation with the above code using sqlite_async.
  2. Notice that the insert does not return the ID of the inserted data.

Environment:
  - Package: 
       sqlite_async: ^0.9.0
       sqlite3_flutter_libs: ^0.5.24
  - Flutter version: │ 3.24.2

**Comment by rkistner** [comment]
You can use `await db.execute('INSERT INTO ... RETURNING id')`, which is a lot more flexible than just getting the last inserted rowid. See the [SQLite docs](https://www.sqlite.org/lang_returning.html) for details.

**Comment by slymnyg** [comment]
Thank you, @rkistner!Thanks for the help, @rkistner! It would be great if the package documentation included an example of this method, as it could make things easier for other developers too.
