### ISSUE TITLE
Using drift migration to create tables

### ISSUE THREAD

**Issue by cl3m** [powersync-ja/sqlite_async.dart#76]
I'm trying to use drift_sqlite_async but the tables are not created. There is an example of usage with migration : https://github.com/powersync-ja/sqlite_async.dart/blob/main/packages/drift_sqlite_async/example/with_migrations.dart

But at line 36 the table are made manually with a sqlite statement (CREATE TABLE). Do you have an example where drift make the table ? Is it something not supported yet ?

**Comment by rkistner** [comment]
Thanks for reporting the issue - that is indeed a bug in the implementation and example.

We'll release a fix soon.

**Comment by rkistner** [comment]
Fixed in drift_sqlite_async 0.2.0.
