### ISSUE TITLE
Memory db for unit test?

### ISSUE THREAD

**Issue by dfdgsdfg** [powersync-ja/sqlite_async.dart#79]
Can I have memory db for unit test?

- https://pub.dev/documentation/sqlite_async/latest/sqlite3/SqlFlag/SQLITE_OPEN_MEMORY-constant.html
- https://pub.dev/documentation/sqlite3/latest/sqlite3/Sqlite3/openInMemory.html

**Comment by rkistner** [comment]
See the discussion here: https://github.com/powersync-ja/sqlite_async.dart/discussions/13

We will support this eventually, but for now you can use the workaround in that discussion to create an unique database per test.
